

export const GET_LOGIN_LOAD = "GET_LOGIN_LOAD";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAIL = "GET_LOGIN_FAIL";


export const REGISTER_LOAD = "REGISTER_LOAD";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT ="LOGOUT";

export const GET_PROFILE_LOAD = "GET_PROFILE_LOAD";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";




