export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAIL = "GET_RESTAURANTS_FAIL";
export const GET_RESTAURANTS_LOAD = "GET_RESTAURANTS_LOAD";

export const GET_ONE_RESTAURANT_SUCCESS = "GET_ONE_RESTAURANT_SUCCESS";

export const GET_ADDRESSES_SUCCESS = "GET_ADDRESSES_SUCCESS";
export const GET_ADDRESSES_FAIL = "GET_ADDRESSES_FAIL";
export const GET_ADDRESSES_LOAD = "GET_ADDRESSES_LOAD";

export const GET_ONE_ADDRESS_SUCCESS = "GET_ONE_ADDRESS_SUCCESS";