export const GET_REVIEW_LOAD = "GET_REVIEW_LOAD";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";
export const POST_REVIEW_LOAD = " POST_REVIEW_LOAD";
export const POST_REVIEW_SUCCESS = " POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAIL = " POST_REVIEW_FAIL";